// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagementNTAPI.Data.Entities;

public partial class School
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual Principal Principal { get; set; }

    public virtual ICollection<Professor> Professor { get; set; } = new List<Professor>();
}