// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagementNTAPI.Data.Entities;

public partial class StudentSubject
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int SubjectId { get; set; }

    public bool IsMajor { get; set; }

    public virtual Student Student { get; set; }

    public virtual Subject Subject { get; set; }
}